---
- hosts: "*_ansible" 

  tasks:
  - name: Post license key
    uri:
      url: https://localhost/api/v2/config/
      method: POST
      user: admin
      password: "{{admin_password}}"
      body: "{{ tower_license }}"
      body_format: json
      validate_certs: False
