- name: Destroy lab instances in AWS
  hosts: localhost
  connection: local
  become: no
  gather_facts: yes
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  vars:
    ec2_exact_count: 0
    ec2_wait: no

  roles:
    - manage_ec2_instances

  post_tasks:
    - name: Remove inventory files
      file: path="{{ item }}" state=absent
      with_fileglob: "{{ playbook_dir }}/*.txt"
      register: removal
      changed_when: removal|success
